# Generated by Django 5.2.4 on 2025-07-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название остановки')),
                ('latitude', models.FloatField(verbose_name='Координаты широты')),
                ('longitude', models.FloatField(verbose_name='Координаты долготы')),
                ('transport_types', models.JSONField(default=list, verbose_name='Тип приходящего транспорта')),
                ('next_stops', models.ManyToManyField(blank=True, related_name='previous_stops', to='transit.stop', verbose_name='Следующие остановки')),
            ],
            options={
                'verbose_name': 'Остановка',
                'verbose_name_plural': 'Остановки',
                'ordering': ['name'],
            },
        ),
    ]
