# Generated by Django 5.2.4 on 2025-07-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='transport_types',
            field=models.CharField(choices=[('bus', 'Автобусная'), ('trolley', 'Троллейбусная'), ('bus-trolley', 'Автобусная-троллейбусная'), ('tram', 'Трамвайная')], max_length=200, verbose_name='Тип приходящего транспорта'),
        ),
    ]
